server:
  port: 8080

spring:
  application:
    name: mybole
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybole?serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234





